name = "hex-berlekamp"
defaultTargets = ["HexBerlekamp", "HexBerlekampTests"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "63d11e9652020e83629808977bff618e99d21234"

[[require]]
name = "HexMatrix"
git = "https://github.com/leanprover/hex-matrix.git"
rev = "e76a18ae921d8d8907c8ea37235a0ca5b94698cd"

[[require]]
name = "HexRowReduce"
git = "https://github.com/leanprover/hex-row-reduce.git"
rev = "65ca599bf2cde1d16ac493b1efb84a1bfd36f105"

[[require]]
name = "HexGFqRing"
git = "https://github.com/leanprover/hex-gfq-ring.git"
rev = "56dd5a199ee4a63710f68260eb82bc4c2aade9f7"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "365881fb205210e8d27c5eb011f7ddb3fe020373"

[[lean_lib]]
name = "HexBerlekamp"

[[lean_lib]]
name = "HexBerlekampTests"
globs = ["HexBerlekamp.FactorTacticTests"]
