name = "hex-berlekamp"
defaultTargets = ["HexBerlekamp", "HexBerlekampTests"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "4a3d3a4eb92596a8e42fedd20db008d8167362fa"

[[require]]
name = "HexMatrix"
git = "https://github.com/leanprover/hex-matrix.git"
rev = "ce6c24451327c1a7ddfea3cd31739966f3622038"

[[require]]
name = "HexRowReduce"
git = "https://github.com/leanprover/hex-row-reduce.git"
rev = "a4679e2cef4589046b9e28b65c7da2df88f7ea12"

[[require]]
name = "HexGFqRing"
git = "https://github.com/leanprover/hex-gfq-ring.git"
rev = "0f717436fbfb270b39cea5b4d8fc5746341c6321"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "a3ab4fd9a79efbe6b07337836b3b5828d22d65a6"

[[lean_lib]]
name = "HexBerlekamp"

[[lean_lib]]
name = "HexBerlekampTests"
globs = ["HexBerlekamp.FactorTacticTests"]
