/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexMatrix.Strassen
public import HexModArith.HotLoop
public import HexArith.Barrett.Accumulator

public section

/-!
Delayed-reduction Barrett base kernel as a demonstration `StrassenConfig`.

The default `StrassenConfig` base kernel (`strassenDefault`) reduces modulo `p`
after every multiply-add. This module supplies a non-default configuration for
the Barrett-reduced prime field `ZMod64 p`: a base kernel
whose dot product accumulates one-word residue products in the two-word
accumulator and reduces modulo `p` only periodically (`delayedDot`, built on the
`HexArith.Barrett.Accumulator` fold `foldReduce`).

It lives here, above both `HexMatrix` and the Barrett layer, because the kernel
needs `Matrix`/`StrassenConfig` *and* `Hex.BarrettCtx` in scope, and the placement
rule forbids `hex-arith`/`hex-mod-arith` from importing `HexMatrix` (that would
invert the released dependency order). `HexBerlekamp` already imports `HexMatrix`
and is the library that consumes the prime-field multiply.

`delayedDot_eq_dotProduct` proves the delayed dot product equals the naive
`Vector.dotProduct` on `ZMod64 p`, from which `strassenBarrett_valid` follows: the
config is `Valid`, so `mulStrassen (strassenBarrett ctx)` still equals the
reference `mul`.

**Measured outcome (honesty constraint (b)).** `strassenBarrett` is the shipped
performance demonstration: benchmarked against `strassenDefault` at `p = 5`,
`65537`, and `2^31 - 1`, its leaf kernel is `2.93`–`16.84×` faster and full
Strassen is `13.32`–`15.30×` faster across the committed square and rectangular
cases; matched-cutoff controls are `5.68`–`15.80×`. The long leaf contractions
`12289` and `20481` cross the 4096-term reduction window three and five times.
A window sweep measures the periodic-loop cost at `3.9`–`5.4%` against an
effectively single-flush loop. The executable path is engineered for this: the
scalar tail-recursive loops `delayedDotLoop`/`delayedDotRun` keep the two-word
accumulator in machine words
(allocation-free, carry inlined as a wraparound compare rather than an
`UInt64.addCarry` extern call, window counter dropped entirely on the
`m < barrettWindow` fast path), `barrettBaseMul` materializes both operand-row
families once (mirroring `mulImpl`), and `radixResidue` computes `2^64 % p` in
machine words. Each piece is verified against the unchanged `foldReduce`
reference. The committed comparison lives in
`reports/figures/strassen-base-kernel-comparison.svg`,
regenerated by `lake exe hexstrassen_compare` and
`scripts/plots/strassen-base-kernel-comparison.py`.
-/

namespace Hex

open Hex.Matrix

variable {p : Nat} [ZMod64.Bounds p] {m : Nat}

/-- The one-word residue product `a * b` has no `UInt64` wraparound: both factors
are below `p < 2^31`, so the product is below `2^62 < 2^64`. -/
private theorem toNat_prodWord (a b : ZMod64 p) :
    (a.toUInt64 * b.toUInt64).toNat = a.toNat * b.toNat := by
  have hp : p < 2 ^ 31 := ZMod64.Bounds.pLtR (p := p)
  have ha : a.toNat < 2 ^ 31 := Nat.lt_trans a.toNat_lt hp
  have hb : b.toNat < 2 ^ 31 := Nat.lt_trans b.toNat_lt hp
  have hlt : a.toNat * b.toNat < UInt64.word := by
    have h1 : a.toNat * b.toNat < 2 ^ 31 * 2 ^ 31 := Nat.mul_lt_mul'' ha hb
    have h2 : (2 : Nat) ^ 31 * 2 ^ 31 ≤ UInt64.word := by
      rw [UInt64.word, ← Nat.pow_add]
      exact Nat.pow_le_pow_right (by decide) (by decide)
    omega
  simpa [UInt64.toNat_mul, UInt64.size, UInt64.word, ZMod64.toUInt64_eq_val,
    ZMod64.toNat_eq_val] using Nat.mod_eq_of_lt hlt

/-- Correspondence lemma: the `ZMod64` dot-product fold, read through `toNat`, is the
residue modulo `p` of the running accumulator plus the `Nat` sum of the remaining
one-word products (`wordsSum` of the mapped list). Proved by list induction with a
generalized accumulator. -/
private theorem toNat_dotFoldl (u v : Vector (ZMod64 p) m) :
    ∀ (l : List (Fin m)) (acc : ZMod64 p),
      (l.foldl (fun a i => a + u[i] * v[i]) acc).toNat =
        (acc.toNat +
          BarrettCtx.wordsSum (l.map (fun i => u[i].toUInt64 * v[i].toUInt64))) % p := by
  intro l
  induction l with
  | nil =>
    intro acc
    simp only [List.foldl_nil, List.map_nil, BarrettCtx.wordsSum_nil, Nat.add_zero]
    exact (Nat.mod_eq_of_lt acc.toNat_lt).symm
  | cons i rest ih =>
    intro acc
    have hstep : (acc + u[i] * v[i]).toNat = (acc.toNat + u[i].toNat * v[i].toNat) % p := by
      show (ZMod64.add acc (ZMod64.mul u[i] v[i])).toNat = _
      rw [ZMod64.toNat_add, ZMod64.toNat_mul, Nat.add_mod_mod]
    simp only [List.foldl_cons, List.map_cons, BarrettCtx.wordsSum_cons]
    rw [ih (acc + u[i] * v[i]), hstep, toNat_prodWord u[i] v[i], Nat.mod_add_mod,
      Nat.add_assoc]

/-- The naive `ZMod64` dot product, read through `toNat`, is the residue modulo
`p` of the `Nat` sum of the one-word products. -/
private theorem toNat_dotProduct (u v : Vector (ZMod64 p) m) :
    (Vector.dotProduct u v).toNat =
      BarrettCtx.wordsSum
        ((List.finRange m).map (fun i => u[i].toUInt64 * v[i].toUInt64)) % p := by
  have h := toNat_dotFoldl u v (List.finRange m) 0
  have hz : (0 : ZMod64 p).toNat = 0 := ZMod64.toNat_zero
  rw [hz, Nat.zero_add] at h
  exact h

/-- **Delayed-reduction Barrett dot product.** Accumulates each one-word residue
product `u[i] * v[i]` into the two-word accumulator and reduces modulo `p` only
every `barrettWindow` terms (`foldReduce`), then reduces the final partial window.
The window is fixed and independent of the length `m`, so this is correct for
every inner dimension. -/
@[expose]
def delayedDot (ctx : Hex.BarrettCtx p) (u v : Vector (ZMod64 p) m) : ZMod64 p :=
  ZMod64.ofNat p
    (BarrettCtx.foldReduce ctx.toUInt64Ctx
      ((List.finRange m).map (fun i => u[i].toUInt64 * v[i].toUInt64))).toNat

/-- Allocation-free scalar loop backing `delayedDotImpl`. The two-word
accumulator `(lo, hi)` and the window counter are threaded as *scalar* arguments
rather than a boxed `(UInt64 × UInt64 × Nat)` tuple, so the compiled loop keeps
`lo`/`hi` in machine words with no per-term heap traffic. Each one-word product
`u[i] * v[i]` is added with an inline carry (the wraparound compare
`lo + q < lo`), avoiding the `UInt64.addCarry` extern call, and the two-word
value is flushed through `accReduce` at every `barrettWindow` terms and once more
at the end. The per-step state transition matches `BarrettCtx.accStep`
(`accStep_eq_inline`), so the loop computes exactly `foldReduce`
(`delayedDotLoop_eq_foldl`). (The repeated product subterm is written out rather
than `let`-bound so the equations rewrite cleanly in the proofs below; the
compiler's CSE emits it once.) -/
def delayedDotLoop (ctx : Hex.BarrettCtx p) (u v : Vector (ZMod64 p) m) :
    Nat → UInt64 → UInt64 → Nat → UInt64
  | i, lo, hi, count =>
    if h : i < m then
      if count + 1 = BarrettCtx.barrettWindow then
        delayedDotLoop ctx u v (i + 1)
          (BarrettCtx.accReduce ctx.toUInt64Ctx (BarrettCtx.radixResidue ctx.toUInt64Ctx)
            (lo + u[i].toUInt64 * v[i].toUInt64)
            (hi + (if lo + u[i].toUInt64 * v[i].toUInt64 < lo then 1 else 0)))
          0 0
      else
        delayedDotLoop ctx u v (i + 1)
          (lo + u[i].toUInt64 * v[i].toUInt64)
          (hi + (if lo + u[i].toUInt64 * v[i].toUInt64 < lo then 1 else 0))
          (count + 1)
    else
      BarrettCtx.accReduce ctx.toUInt64Ctx (BarrettCtx.radixResidue ctx.toUInt64Ctx) lo hi
  termination_by i => m - i
  decreasing_by all_goals omega

/-- Count-free fast path of `delayedDotLoop`, usable when the whole dot product
fits in a single window (`m < barrettWindow`). This includes the ordinary square
Strassen leaves; the generic base-kernel signature also admits larger inner
dimensions that use the windowed loop. When this path applies, the accumulator
never flushes mid-run, so the window counter and its per-term check disappear
from the inner loop entirely. The carry is written as an
unconditional add of an `if`-valued bit so the C compiler can lower it to a
flag-based `setb`/`cmov` rather than a data-dependent branch. -/
def delayedDotRun (ctx : Hex.BarrettCtx p) (u v : Vector (ZMod64 p) m) :
    Nat → UInt64 → UInt64 → UInt64
  | i, lo, hi =>
    if h : i < m then
      delayedDotRun ctx u v (i + 1)
        (lo + u[i].toUInt64 * v[i].toUInt64)
        (hi + (if lo + u[i].toUInt64 * v[i].toUInt64 < lo then 1 else 0))
    else
      BarrettCtx.accReduce ctx.toUInt64Ctx (BarrettCtx.radixResidue ctx.toUInt64Ctx) lo hi
  termination_by i => m - i
  decreasing_by all_goals omega

/-- Allocation-free implementation of `delayedDot`: selection once per dot product
on whether the length fits in a single window, then run a scalar loop that never
materializes the `List.finRange m` product-word list nor a boxed accumulator
tuple (`delayedDotRun` without the window counter when `m < barrettWindow`, the
windowed `delayedDotLoop` otherwise). Swapped in for compiled code by the
`@[csimp]` below; `delayedDot` stays the list-based reference form for proofs,
mirroring `Vector.dotProduct`/`dotProductImpl`. -/
@[expose]
def delayedDotImpl (ctx : Hex.BarrettCtx p) (u v : Vector (ZMod64 p) m) : ZMod64 p :=
  if m < BarrettCtx.barrettWindow then
    ZMod64.ofNat p (delayedDotRun ctx u v 0 0 0).toNat
  else
    ZMod64.ofNat p (delayedDotLoop ctx u v 0 0 0 0).toNat

/-- The windowed scalar loop computes the `accStep` fold of the remaining
product words, flushed through `accReduce`: the loop-to-fold correspondence behind the
`@[csimp]`. Stated from an arbitrary start state so the induction goes through;
list-level rewrites are combined under `congrArg` of the `accReduce` wrapper, so
the Barrett machinery is never rewritten into (mirroring the previous fold
proof's `kabstract` caution). -/
private theorem delayedDotLoop_eq_foldl (ctx : Hex.BarrettCtx p) (u v : Vector (ZMod64 p) m)
    (i : Nat) (lo hi : UInt64) (count : Nat) :
    delayedDotLoop ctx u v i lo hi count =
      BarrettCtx.accReduce ctx.toUInt64Ctx (BarrettCtx.radixResidue ctx.toUInt64Ctx)
        ((((List.finRange m).drop i).map (fun j => u[j].toUInt64 * v[j].toUInt64)).foldl
          (BarrettCtx.accStep ctx.toUInt64Ctx) (lo, hi, count)).1
        ((((List.finRange m).drop i).map (fun j => u[j].toUInt64 * v[j].toUInt64)).foldl
          (BarrettCtx.accStep ctx.toUInt64Ctx) (lo, hi, count)).2.1 := by
  fun_induction delayedDotLoop ctx u v i lo hi count with
  | case1 i lo hi count h hwin ih =>
    -- Flush step: the fold's `accStep` takes the `ite_eq_left` branch.
    have hcomb :
        (((List.finRange m).drop i).map (fun j => u[j].toUInt64 * v[j].toUInt64)).foldl
            (BarrettCtx.accStep ctx.toUInt64Ctx) (lo, hi, count) =
          (((List.finRange m).drop (i + 1)).map
              (fun j => u[j].toUInt64 * v[j].toUInt64)).foldl
            (BarrettCtx.accStep ctx.toUInt64Ctx)
            (BarrettCtx.accReduce ctx.toUInt64Ctx (BarrettCtx.radixResidue ctx.toUInt64Ctx)
              (lo + u[i].toUInt64 * v[i].toUInt64)
              (hi + (if lo + u[i].toUInt64 * v[i].toUInt64 < lo then 1 else 0)), 0, 0) := by
      rw [List.drop_eq_getElem_cons (by simpa using h), List.map_cons, List.foldl_cons,
        BarrettCtx.accStep_eq_inline, ite_eq_left hwin]
      simp only [List.getElem_finRange, Fin.getElem_fin, Fin.val_cast]
    exact ih.trans (congrArg
      (fun s : UInt64 × UInt64 × Nat =>
        BarrettCtx.accReduce ctx.toUInt64Ctx (BarrettCtx.radixResidue ctx.toUInt64Ctx)
          s.1 s.2.1)
      hcomb).symm
  | case2 i lo hi count h hwin ih =>
    -- In-window step: the fold's `accStep` takes the `ite_eq_right` branch.
    have hcomb :
        (((List.finRange m).drop i).map (fun j => u[j].toUInt64 * v[j].toUInt64)).foldl
            (BarrettCtx.accStep ctx.toUInt64Ctx) (lo, hi, count) =
          (((List.finRange m).drop (i + 1)).map
              (fun j => u[j].toUInt64 * v[j].toUInt64)).foldl
            (BarrettCtx.accStep ctx.toUInt64Ctx)
            (lo + u[i].toUInt64 * v[i].toUInt64,
              hi + (if lo + u[i].toUInt64 * v[i].toUInt64 < lo then 1 else 0),
              count + 1) := by
      rw [List.drop_eq_getElem_cons (by simpa using h), List.map_cons, List.foldl_cons,
        BarrettCtx.accStep_eq_inline, ite_eq_right hwin]
      simp only [List.getElem_finRange, Fin.getElem_fin, Fin.val_cast]
    exact ih.trans (congrArg
      (fun s : UInt64 × UInt64 × Nat =>
        BarrettCtx.accReduce ctx.toUInt64Ctx (BarrettCtx.radixResidue ctx.toUInt64Ctx)
          s.1 s.2.1)
      hcomb).symm
  | case3 i lo hi count h =>
    -- Exhausted: nothing left to fold.
    have hfold :
        (((List.finRange m).drop i).map (fun j => u[j].toUInt64 * v[j].toUInt64)).foldl
            (BarrettCtx.accStep ctx.toUInt64Ctx) (lo, hi, count) = (lo, hi, count) := by
      rw [List.drop_eq_nil_of_le (by simpa using Nat.le_of_not_lt h)]
      rfl
    exact (congrArg
      (fun s : UInt64 × UInt64 × Nat =>
        BarrettCtx.accReduce ctx.toUInt64Ctx (BarrettCtx.radixResidue ctx.toUInt64Ctx)
          s.1 s.2.1)
      hfold).symm

/-- The count-free fast path agrees with the windowed loop whenever the remaining
run cannot fill the window (`count + m < barrettWindow + i`), which holds from
the start state exactly when `m < barrettWindow`: the flush branch is never
taken, so the counter is dead. -/
private theorem delayedDotRun_eq_loop (ctx : Hex.BarrettCtx p) (u v : Vector (ZMod64 p) m)
    (i : Nat) (lo hi : UInt64) :
    ∀ (count : Nat), count + m < BarrettCtx.barrettWindow + i →
      delayedDotRun ctx u v i lo hi = delayedDotLoop ctx u v i lo hi count := by
  fun_induction delayedDotRun ctx u v i lo hi with
  | case1 i lo hi h ih =>
    intro count hcount
    have hne : ¬ (count + 1 = BarrettCtx.barrettWindow) := by omega
    rw [delayedDotLoop, dite_eq_left h, ite_eq_right hne]
    exact ih (count + 1) (by omega)
  | case2 i lo hi h =>
    intro count _
    rw [delayedDotLoop, dite_eq_right h]

/-- The reference delayed dot product agrees with the windowed implementation,
registered `@[csimp]` so compiled code runs `delayedDotImpl` while proofs keep
reasoning about `delayedDot`. -/
@[csimp] theorem delayedDot_eq_impl : @delayedDot = @delayedDotImpl := by
  funext p inst m ctx u v
  -- The loop from the empty start state computes exactly `foldReduce` (the
  -- `drop 0` and the `foldReduce` `let` both reduce definitionally).
  have hloop : delayedDotLoop ctx u v 0 0 0 0 =
      BarrettCtx.foldReduce ctx.toUInt64Ctx
        ((List.finRange m).map (fun i => u[i].toUInt64 * v[i].toUInt64)) :=
    delayedDotLoop_eq_foldl ctx u v 0 0 0 0
  by_cases hm : m < BarrettCtx.barrettWindow
  · have hrun : delayedDotRun ctx u v 0 0 0 = delayedDotLoop ctx u v 0 0 0 0 :=
      delayedDotRun_eq_loop ctx u v 0 0 0 0 (by omega)
    calc delayedDot ctx u v
        = ZMod64.ofNat p (delayedDotRun ctx u v 0 0 0).toNat :=
          congrArg (fun w : UInt64 => ZMod64.ofNat p w.toNat) (hrun.trans hloop).symm
      _ = delayedDotImpl ctx u v := by rw [delayedDotImpl, ite_eq_left hm]
  · calc delayedDot ctx u v
        = ZMod64.ofNat p (delayedDotLoop ctx u v 0 0 0 0).toNat :=
          congrArg (fun w : UInt64 => ZMod64.ofNat p w.toNat) hloop.symm
      _ = delayedDotImpl ctx u v := by rw [delayedDotImpl, ite_eq_right hm]

/-- **Correctness of the delayed dot product.** The periodically-reduced dot
product equals the naive `Vector.dotProduct` on `ZMod64 p`: reduction modulo `p`
is a ring homomorphism, so reducing periodically has the same residue as reducing
at every step. -/
theorem delayedDot_eq_dotProduct (ctx : Hex.BarrettCtx p) (u v : Vector (ZMod64 p) m) :
    delayedDot ctx u v = Vector.dotProduct u v := by
  apply ZMod64.ext_toNat
  rw [delayedDot, ZMod64.toNat_ofNat, BarrettCtx.toNat_foldReduce, ctx.modulus_eq,
    Nat.mod_mod, toNat_dotProduct]

/-- **Delayed-reduction base kernel**, selecting on the runtime inner dimension:
the delayed dot product is the fast path once the dot-product length is nontrivial
(`2 ≤ m`), and it falls back to the naive `mulImpl` on the trivial residual shapes.
Mirroring `mulImpl`, the fast path transposes `N` once, materializes the
transposed rows once, and materializes each row of `M` once per output row. Every
dot product then runs over two contiguous rows with no per-entry row copy. Both
branches equal the reference `mul`, so the config built from this is `Valid`. -/
@[expose]
def barrettBaseMul (ctx : Hex.BarrettCtx p) {n m k : Nat}
    (M : Matrix (ZMod64 p) n m) (N : Matrix (ZMod64 p) m k) : Matrix (ZMod64 p) n k :=
  if 2 ≤ m then
    let Ntr := (Matrix.transpose N).rows
    Matrix.ofRows (Vector.ofFn fun i =>
      let ri := Matrix.getRow M i
      Vector.ofFn fun j => delayedDot ctx ri Ntr[j])
  else
    Matrix.mulImpl M N

/-- The delayed-reduction base kernel agrees with the reference `mul` on every
input and shape. -/
theorem barrettBaseMul_eq_mul (ctx : Hex.BarrettCtx p) {n m k : Nat}
    (M : Matrix (ZMod64 p) n m) (N : Matrix (ZMod64 p) m k) :
    barrettBaseMul ctx M N = Matrix.mul M N := by
  unfold barrettBaseMul
  split
  · apply Matrix.ext_getElem
    intro i j
    have h :
        (Matrix.ofRows (Vector.ofFn fun a : Fin n =>
          let ra := Matrix.getRow M a
          Vector.ofFn fun b : Fin k => delayedDot ctx ra (Matrix.transpose N).rows[b]))[i][j] =
          delayedDot ctx (Matrix.getRow M i) (Matrix.getRow (Matrix.transpose N) j) := by
      rw [Matrix.getElem_ofRows]
      simp only [Fin.getElem_fin, Vector.getElem_ofFn, Fin.eta, Matrix.getElem_rows]
    rw [h, delayedDot_eq_dotProduct,
      show Matrix.getRow (Matrix.transpose N) j = Matrix.row (Matrix.transpose N) j from rfl,
      Matrix.row_transpose]
    exact (Matrix.getElem_mul M N i j).symm
  · rw [Matrix.mul_eq_mulImpl]

/-- **The shipped performance demonstration config**: the delayed-reduction
Barrett base kernel over the prime field `ZMod64 p`, taking the `Hex.BarrettCtx`.
Measurably faster than `strassenDefault` at every measured square and
rectangular shape (see the measured outcome in the module docstring and the
committed comparison in `reports/figures/`). Its cutoff is pinned at `128`, the
delayed kernel's own measured crossover: the delayed dot product has a lower
per-term cost but a per-dot-product reduction constant, so it profits from
longer base-case dot products than the default kernel does (the default cutoff
is measured separately and may move). -/
@[expose]
def strassenBarrett (ctx : Hex.BarrettCtx p) : Matrix.StrassenConfig (ZMod64 p) where
  cutoff := 128
  baseMul {_n _m _k} M N := barrettBaseMul ctx M N

/-- The delayed config is `Valid`: its base kernel equals `mul`, so
`mulStrassen (strassenBarrett ctx)` still computes the reference product. -/
theorem strassenBarrett_valid (ctx : Hex.BarrettCtx p) :
    (strassenBarrett ctx).Valid := by
  intro n m k X Y
  exact barrettBaseMul_eq_mul ctx X Y

/-- **A trivial alternate config** that plugs the naive `mulImpl` base kernel
into a non-default `StrassenConfig` (with a distinct cutoff): the minimal
example of the pluggable-base-kernel path, with a verified-`Valid` config
supplied by the caller and no performance claim attached. The performance
example is `strassenBarrett` above. -/
@[expose]
def strassenDemo : Matrix.StrassenConfig (ZMod64 p) where
  cutoff := 48
  baseMul := Matrix.mulImpl

/-- The trivial alternate config is `Valid`: its naive base kernel equals
`mul` by `mul_eq_mulImpl`. -/
theorem strassenDemo_valid : (strassenDemo (p := p)).Valid := by
  intro n m k X Y
  show Matrix.mulImpl X Y = Matrix.mul X Y
  rw [Matrix.mul_eq_mulImpl]

end Hex
